name: Docker

on:
  schedule:
    - cron: '00 01 * * *'
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  IMAGE_NAME: n9org/inspect

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: 
          - 7.3-debian-11

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          build-args: |
            BASE_IMAGE_VERSION=${{ matrix.version }}
          tags: ${{ env.IMAGE_NAME }}:${{ matrix.version }}
